name: Deploy stage

on:
  push:
    branches:
      - "homologacao"

jobs:
  build:
    name: Deploy Stage
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./*"
          target: "/home/deploymillion/bff-app/stage"

      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Set the PATH to include the NVM directory
            export PATH=/home/deploymillion/.nvm/versions/node/v16.20.2/bin:$PATH
            echo "Updated PATH: $PATH"
            cd /home/deploymillion/bff-app/stage
            npm install
